version: "3.0"
services:
    backend:
        container_name: "backend"
        build: ./backend/
        ports:
        - "3001:3001"
    pg:
        image: "postgres:12"
        container_name: "postgres"
        ports:
        - "5432:5432"
        volumes:
        - ./pgdata/db_data:/var/lib/postgresql/data
        - ./pgdata/initDB:/docker-entrypoint-initdb.d/
        environment: 
            POSTGRES_DB: "db"
            POSTGRES_PASSWORD: "1"
            PGDATA: ./pgdata:/var/lib/postgresql/data
    frontend:
        container_name: "frontend"
        build: ./frontend/
        ports:
            - "3000:3000"
        stdin_open: true
